# Generated by Django 2.1.1 on 2018-09-19 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_type',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='blog.BlogType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=64),
        ),
    ]
