# Generated by Django 2.1.1 on 2018-09-20 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180919_0810'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtype',
            name='type_e_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
